### ISSUE TITLE
Simplify implementation

### ISSUE THREAD

**Issue by x1unix** [JoshuaDoes/sudo#1]
Hello. There is a much simpler way to implement a sudo tool.

The idea is create an application that starts a process with specified arguments but will request Administrator rights on start (aka elevation).

```go
args := os.Args[1:]
cmdName := args[0]
cmdArgs := args[1:]

cmd := exec.Cmd(cmdName, cmdArgs...)
cmd.Run()
```

This can be achieved by embedding [application manifest](http://msdn.microsoft.com/en-us/library/windows/desktop/aa374191%28v=vs.85%29.aspx) into a `sudo` executable.

[This tool](https://github.com/akavel/rsrc) might be useful for this.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
    <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
        <security>
            <requestedPrivileges>
                <requestedExecutionLevel level="requireAdministrator" uiAccess="false"/>
            </requestedPrivileges>
        </security>
    </trustInfo>
</assembly>
```

**Comment by JoshuaDoes** [comment]
I haven't yet written a readme explaining as such, but the primary reason for having a user-mode host process is so that the stdpipe of the elevated process doesn't get detached from an existing user shell. Windows does this as a security precaution, but it interrupts data I/O in such cases and also can cause frustrations running quick elevated tasks that you wish to keep to your current shell.

If security is a concern, unprivileged user accounts shouldn't be granted permission to run sudo to begin with, let alone other admin programs. This is mostly just a convenience injection inspired by the Linux counterpart, and I'll update it with time to aid in standard local security (such as key exchanges) and other conveniences such as a sudo session that can use goroutines to manage as many elevated tasks as you need without running into port selection issues.

I'll close this for now, but I highly encourage you to make the alternative implementation yourself if it's something you're interested in!

**Comment by x1unix** [comment]
@JoshuaDoes thank you for a reply. Have you thought about using names pipes or sockets instead of HTTP server?

**Comment by JoshuaDoes** [comment]
> Have you thought about using names pipes or sockets instead of HTTP server?

I'm not sure how you got that I was using an HTTP connection from the above or from the code. I'm currently using TCP sockets - and while I may consider adding support for named pipes and switching to them to use by default after the reading I've done, at the moment a localhost TCP connection opens the door for me to also work on adding Linux and Android support without having to rewrite too much. And when I get around to adding named pipes for Windows, I can also add Unix sockets for Linux and leave in localhost TCP as the fallback for Android.
